services:
  microfrontend-auth:
    build:
      context: frontend/microfrontend
      dockerfile: auth/.dockerfile
    ports:
      - "8001:8001"
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8001 || exit 1
      interval: 10s
      retries: 50
      start_period: 10s
      timeout: 5s

  microfrontend-cards:
    build:
      context: frontend/microfrontend
      dockerfile: cards/.dockerfile
    ports:
      - "8003:8003"
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8003 || exit 1
      interval: 10s
      retries: 50
      start_period: 10s
      timeout: 5s

  microfrontend-profile:
    build:
      context: frontend/microfrontend
      dockerfile: profile/.dockerfile
    ports:
      - "8002:8002"
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8002 || exit 1
      interval: 10s
      retries: 50
      start_period: 10s
      timeout: 5s

  microfrontend-host:
    build:
      context: frontend
      dockerfile: .dockerfile
    ports:
      - "8000:8000"
    depends_on:
      microfrontend-auth:
        condition: service_healthy
      microfrontend-cards:
        condition: service_healthy
      microfrontend-profile:
        condition: service_healthy